version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/maxmellon/The-Program-Language-Go

    steps:
      - checkout
      - run: go get -u github.com/golang/lint/golint
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: golint ./...
      - run:
          name: exec
          command: |
            for i in ch*/ex*/run.sh
            do
              $i
            done
      - run:
          name: test
          command: |
            for i in ch*/ex*/test.sh
            do
              $i
            done
