version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/maxmellon/The-Program-Language-Go

    steps:
      - checkout
      - run: go get -u github.com/golang/lint/golint
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: golint ./...
      - run: ch*/ex*/run.sh
      - run: ch*/ex*/test.sh
